name: Create Gource Video
on:
  workflow_dispatch:
    inputs:
      gource_resolution:
        description: "Used gource resolution."
        type: choice
        required: true
        default: 1080p
        options:
          - 2160p
          - 1440p
          - 1080p
          - 720p

jobs:
  create_video:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Extract branch name
        id: get_branch_name
        shell: python
        run: |
          import os

          branch_name = os.environ["GITHUB_REF"].split("/")[-1]

          print(f"Setting brach name to: {branch_name}")

          with open(os.getenv("GITHUB_OUTPUT"), "a", encoding="utf8") as f:
              f.writelines([f"branch_name={branch_name}"])

      - name: Copy avatars
        run: python prepare-build.py

      - name: "Gource Action"
        uses: nbprojekt/gource-action@v1
        with:
          git_url: https://github.com/glotaran/pyglotaran
          gource_title: pyglotaran
          logo_url: "https://raw.githubusercontent.com/glotaran/pyglotaran/main/docs/source/images/glotaran.png?raw=true"
          avatars_url: "./avatars"
          gource_resolution: ${{ github.event.inputs.gource_resolution }}
          gource_fps: 60
          gource_font_size: 40

      - name: Rename Video
        env:
          branch_name: ${{ steps.get_branch_name.outputs.branch_name }}
        run: mv gource/gource.mp4 "gource/gource_${{ env.branch_name }}.mp4"

      - uses: actions/upload-artifact@v4
        env:
          branch_name: ${{ steps.get_branch_name.outputs.branch_name }}
        with:
          name: gource_${{ env.branch_name }}
          path: ./gource/gource_${{ env.branch_name }}.mp4
